name: Publish package
on:
  push:
    branches: main
    paths:
      - "package.json"
      - ".github/workflows/main.yaml"
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.17.6
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.6
      - name: install
        run: npm install
      - name: patch
        run: node patch.js
      - name: build
        run: npm run build
      - name: write
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
      - name: publish
        run: npm publish --access public
        working-directory: dist
