name: Publish package
on:
  push:
    branches: main
    paths:
      - "package.json"
      - ".github/workflows/main.yaml"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.17.6
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.6
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: publish
        run: npm run publish
        working-directory: dist
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
